### PR TITLE
IGC G record support

### PR DESCRIPTION
**Pull request by dkm**
These 4 commits add support in Gaggle for IGC g-record creation.

The G record is using SHA1-RSA to digitally sign everything written to the igc file.
The ssl/ directory contains a simple C file used to check the signature of a given igc file. It is expected to be run on WXC servers.

Gaggle has its own 3-letters id: XGG, used in the A field of the IGC file.

### CODE REVIEW

**Comment by dkm** [comment]
The last commit should allow galaxy S (ace, Y, maybe more) to workaround a bug (http://code.google.com/p/android/issues/detail?id=23937 ) that is more problematic when mixed with digital signature.

**Comment by sletuffe** [comment]
Maybe I'm late on this, should I merge it ?
I haven't had time to review, but if that doesn't break things for you, it shouldn't break for others ;-)

**Comment by dkm** [comment]
On 06/08/2012 01:24 PM, sylvain letuffe wrote:

> Maybe I'm late on this, should I merge it ?
> I haven't had time to review, but if that doesn't break things for you, it shouldn't break for others ;-)

I'm still waiting for a reply from WXC. I would prefer to see the 
support ready on their side before merging...

**Comment by sletuffe** [comment]
oh ! ok then. You mean you have the rights you need to merge it yourself ?
Then perfect, (I thought this request hasn't been merged yet because it was waiting for me or kevin to do something)

**Comment by dkm** [comment]
On 06/08/2012 01:30 PM, sylvain letuffe wrote:

> oh ! ok then. You mean you have the rights you need to merge it yourself ?
> Then perfect, (I thought this request hasn't been merged yet because it was waiting for me or kevin to do something)

That's also true... I was hoping that someone with better knowledge of 
Gaggle would review my code before I got it merged..

**Comment by sletuffe** [comment]
On vendredi 8 juin 2012, you wrote:

> On 06/08/2012 01:30 PM, sylvain letuffe wrote:
> 
> > oh ! ok then. You mean you have the rights you need to merge it yourself ?
> > Then perfect, (I thought this request hasn't been merged yet because it 
> > was waiting for me or kevin to do something)
> 
> That's also true... I was hoping that someone with better knowledge of 
> Gaggle would review my code before I got it merged..

héhé ! Unfortunetly, that guy is not me ;-)
I'm just hacking around gaggle, and kevin is the one with full knowledge, but 
less time

## 

sly
qui suis-je : http://sly.letuffe.org

**Comment by dkm** [comment]
On 06/08/2012 01:34 PM, sylvain letuffe wrote:

> On vendredi 8 juin 2012, you wrote:
> 
> > On 06/08/2012 01:30 PM, sylvain letuffe wrote:
> > 
> > > oh ! ok then. You mean you have the rights you need to merge it yourself ?
> > > Then perfect, (I thought this request hasn't been merged yet because it
> > > was waiting for me or kevin to do something)
> > 
> > That's also true... I was hoping that someone with better knowledge of
> > Gaggle would review my code before I got it merged..
> 
> héhé ! Unfortunetly, that guy is not me ;-)
> I'm just hacking around gaggle, and kevin is the one with full knowledge, but
> less time

:)

We'll see later about that. I guess this particular PR can be merged 
safely (when I get an answer from WXC...). There may be more problem 
when I will propose bigger changes that are maturing in my own branches :)

Marc

**Comment by dkm** [comment]
Looks like it won't happen before next week (at best)...

**Comment by dkm** [comment]
Guess this won't ever be resurrected :)

**Pull request closed without merging**
