### PR TITLE
As suggested on the list, here are my small propositions

### PR DESCRIPTION
**Pull request by sletuffe**
I'm still strugling with git/github so please excuse my name changes or other errors using that tool

In case of code problem or git usage problem feel free to ask me to modify what I've done

### CODE REVIEW

**Comment by geeksville** [comment]
Thank you so much!  You are the first person besides myself to check into gaggle in a while.  I'm away from my computer tonight, but I'll do a new market build tomorrow.  Let me know if you want to be an admin so you can bless your own future pull requests for this project (I've been neglecting gaggle)

**Comment by sletuffe** [comment]
I'll hapilly be an admin of the project is that can help you save some time. Does this status permits me to close user's issues that are solved as well ?

**Comment by geeksville** [comment]
yes.

On Fri, May 13, 2011 at 2:22 AM, sletuffe
reply@reply.github.com
wrote:

**Comment by geeksville** [comment]
I've added you now.  You can now manipulate the issues database and bless checkins.  Thank you so much - make sure to add your name to the credits ;-).

**Comment by sletuffe** [comment]
thanks a lot for your trust

**Pull request merged**
