### PR TITLE
Competition Class

### PR DESCRIPTION
**Pull request by DawsonLeBrown**
added Competition Class as a configurable option under Preferences>Glider Information>Competition Class

Signed-off-by: Dawson Brown dawson@nhgc.asn.au

refs #35

### CODE REVIEW

**Comment by sletuffe** [comment]
All this works great for me, I've checked the leonardo track upload and it works as expected.

Next step would be to set the glider brand and constructor, but that's gone be much harder given that the list is constantly expanded at leonardo.

I can merge dawson's commits to the master branch, but I'm unsure if I should do it, so I'm letting kevin decide (and if he wants to increase gaggle's version number)

I would personnaly merge, but I don't want to step on kevin's toes ;-)

**Comment by DawsonLeBrown** [comment]
Thanks for testing my changes Sly.

I had initialy expected to be adding the glider brand, constructor etc along with class, but upon reading http://www.paraglidingforum.com/leonardo/doc/direct_upload.html it looks like the Leonardo direct upload feature doesn't support it.

Kevin, I have attempted to match the coding standards you've used so far, but may well have misse the mark. If there are any code style changes you'd like, please let me know and I'll make them.

**Comment by sletuffe** [comment]
I have moved forward with your waiting changes by merging them.

Thanks again for your work dawson !

(I hope kevin won't mind, but it looks like he might be busy with other projects)

**Comment by DawsonLeBrown** [comment]
Yep, he did say he was busy, thanks Sly.

**Comment by sletuffe** [comment]
Your welcome, I guess it whould even be easier if you could merge pull request or commit directly to the master branch, but looks like I don't have enough rights to make this happen.

**Pull request merged**
