### PR TITLE
Add instructions for connect to livetrack24 via UDP.

### PR DESCRIPTION
**Pull request by chanoch**
6 example java classes and a PDF from Manolis on how to go about integrating Gaggle with livetrack24. This includes how to go about testing

### CODE REVIEW

**Comment by dkm** [comment]
Are these files from manolis ? Is it ok to use it in a GPLed software ? Because if it's not the case, we can't use that code and must only read the doc :)

**Comment by chanoch** [comment]
Let me reset this commit and then I'll talk to Manolis about the license for his code. He already provides it free of charge, it might be that he just didn't get around to licensing it free.

**Comment by chanoch** [comment]
Manolis has written back to say that we should derive from his code, giving proper attribution and continue the GPL license and so on, so good news.

**Comment by sletuffe** [comment]
I might seam over doubting, but as I read the copyright on the begining of the NetSendLogin.java file :
// J2ME GPS Track
// Copyright (C) 2006 Dana Peters
// http://www.qcontinuum.org/gpstrack

Manolis is not the copyright owner, but Dana Peters is.
gpstrack seams to be GPL as well so there shouldn't be any problems, but I can't find thoses classes at http://www.qcontinuum.org/gpstrack to be sure.
That would be unrespectfull from our side to use those classes or even derive from it without at least checking the licence, or, if we can't ask kindly to the author.

I'm almost sure there won't be any problems, but, well, better be sure ;-)

**Pull request closed without merging**
