### PR TITLE
Added copright notice to java classes without it.

### PR DESCRIPTION
**Pull request by chanoch**
This one is a bit more tricky - I wasn't sure if all classes that didn't have a copyright notice should have one but just being tidy.

Standardised all current files so that any without a geeksville, google or other copyright notice have one

In addition, a file javadoc change has sneaked in as well as the removal of a couple of redundant imports.

Chanoch

### CODE REVIEW

**Comment by dkm** [comment]
Sorry, this will have to change. I asked kevin about this double licensing (commercial stuff), and he's ok to remove it as it's not useful anymore. So all headers will have to be changed, and correct ownership must be kept. Maybe you can extract only the javadoc changes from the header ones... ?

**Comment by chanoch** [comment]
I can redo the work Marc, that's not a problem. I'm pretty sure any removal of the secondary license needs to be accompanied by a signed release from Kevin, however.

Sorry if I am preaching to the converted but the standard GPL notice would have a copyright notice for the authors (developers) for anyone who has contributed to the code base. In addition, each year that there has been release should be mentioned in the header. So there are a couple of other updates to do.

If Kevin could provide the release for dropping the commercial secondary license, then I'm happy to tidy all that up.

Do you have a list of the people who should be assigned copyright or is Kevin's copyright sufficient?

**Comment by geeksville** [comment]
Hi ya'll,

hereby authorizing changing the license to a standard GPL license.   Please
leave the copyright in my name though (if only for historical karma ;-)).
 If someone radically changes some file, of course I'm fine with them
adding their name to the copyright.

Kevin

**Comment by chanoch** [comment]
Hey, that's excellent news. Thank you.

Does anyone object to moving to GPLv3? It could be useful to be able to include libraries which are Apache 2 licensed (which pretty much all code.google libraries do, for example?)

**Comment by dkm** [comment]
I have no problem moving to GPLv3 :)
As for keeping the name of author, this is not only for karma :) GPL does not mean that you loose ownership ! :)

**Comment by chanoch** [comment]
Closing as I will be submitting a separate and independant pull request for removal of Geeksville commercial license and update of the GPL license to V3 (Gaggle's references to it allowed update to later versions of GPL (from V2.0) at the modifiers discretion which Marc and I have agreed.

**Pull request closed without merging**
